version: 3.2.0
hassio_api: true
slug: nginx_proxy_dev
name: NGINX Home Assistant SSL proxy (DEV)
description: An SSL/TLS proxy
url: https://github.com/skgsergio/ha-addons-dev/tree/main/nginx_proxy_dev
arch:
  - amd64
image: skgsergio/{arch}-addon-nginx_proxy
map:
  - ssl
  - share
options:
  allowlist:
    active: false
    cloudflare: false
    entries: []
  certfile: fullchain.pem
  cloudflare: false
  customize:
    active: false
    default: nginx_proxy_default*.conf
    servers: nginx_proxy/*.conf
  domain: null
  hsts: max-age=31536000; includeSubDomains
  keyfile: privkey.pem
ports:
  443/tcp: 443
  80/tcp: null
schema:
  allowlist:
    active: bool
    cloudflare: bool
    entries:
      - str
  certfile: str
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
  domain: str
  hsts: str
  keyfile: str
